(********************************************************************
 * COPYRIGHT -- MIEtech GmbH & Co. KG
 ********************************************************************
 * Program:	TestMotor
 * File:	Main.st
 * Author:	D.Graf
 * Created:	01.10.2021
 * Changed:	05.01.2020, MM, example changelog discription 1
 *			20.10.2021, DG, Add Motor Functions
 ********************************************************************
 * Motor Program
 ********************************************************************)
	
PROGRAM _INIT
	(* Insert code here *)
	 
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
	 
	
	
	
	
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

